spring.application.name=proyecto
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=RESPONSYSDBABCV8
spring.datasource.password=responsysdbabc
 	
cron.tarea.configuracion= 0 56 09 * * ?
    
cron.monitoreo.configuracion= 0 * * * * ?
  
hora.cron.monitoreo=213
     
cron.cl.respuesta = 0 13 16 * * ?

cron.pet.respuesta = 0 06 16 * * ?
 
numero.registros.enviados.linea=200
	
numero.registros.enviados.campana=200

carga.linea.url=http://localhost:8080/profuturo/api/v1/carga/lista/contacto
validacion.linea.url=http://localhost:8080/profuturo/api/v1/valida/lista/contacto
envio.linea.url=http://localhost:8080/profuturo/api/v1/envio/lista/contacto
respuesta.linea.url=http://localhost:8080/profuturo/api/v1/respuesta/lista/contacto

validacion.campana.url=http://localhost:8080/profuturo/api/v1/valida/extencion/perfil
envio.campana.url=http://localhost:8080/profuturo/api/v1/envio/extencion/perfil
respuesta.campana.url=http://localhost:8080/profuturo/api/v1/respuesta/extencion/perfil


token.url=https://gcw1qbi-api.responsys.ocs.oraclecloud.com/rest/api/v1.3/auth/token
token.auth_type=password
token.user_name=CapgemTest.Integration
token.password=Oracle123#


async.update.cl.afore.url=https://gcw1qbi-api.responsys.ocs.oraclecloud.com/rest/asyncApi/v1.3/lists/AR_AFORE_CL_DEV/members
async.update.cl.sofom.url=https://gcw1qbi-api.responsys.ocs.oraclecloud.com/rest/asyncApi/v1.3/lists/AR_SOFOM_CL_DEV/members
async.update.cl.pensiones.url=https://gcw1qbi-api.responsys.ocs.oraclecloud.com/rest/asyncApi/v1.3/lists/AR_PENSIONES_CL_DEV/members
async.update.cl.prospectos.url=https://gcw1qbi-api.responsys.ocs.oraclecloud.com/rest/asyncApi/v1.3/lists/AR_PROSPECTOS_CL_DEV/members

async.update.pet.afore.url=https://gcw1qbi-api.responsys.ocs.oraclecloud.com/rest/asyncApi/v1.3/lists/AR_AFORE_CL_DEV/listExtensions/BIENVENIDA/members
async.update.pet.sofom.url=https://gcw1qbi-api.responsys.ocs.oraclecloud.com/rest/asyncApi/v1.3/lists/AR_SOFOM_CL_DEV/listExtensions/BIENVENIDA/members
async.update.pet.pensiones.url=https://gcw1qbi-api.responsys.ocs.oraclecloud.com/rest/asyncApi/v1.3/lists/AR_PENSIONES_CL_DEV/listExtensions/BIENVENIDA/members
async.update.pet.prospectos.url=https://gcw1qbi-api.responsys.ocs.oraclecloud.com/rest/asyncApi/v1.3/lists/AR_PROSPECTOS_CL_DEV/listExtensions/BIENVENIDA/members




middleware.cl.url=http://localhost:8080/profuturo/api/v1/cl/middleware
middleware.pet.url=http://localhost:8080/profuturo/api/v1/pet/middleware


polling.status.url=https://gcw1qbi-api.responsys.ocs.oraclecloud.com/rest/asyncApi/v1.3/requests
